---
# tasks file for clone_repo
- name: install git package
  yum: name=git state=latest
  become: true
  become_user: root

- name: Disable SSL
  shell:
    "git config --global http.sslVerify false"

- name: Clone a github repository
  git:
    repo: '{{repository}}'
    dest: "{{project_path}}/"
    accept_hostkey: true
    clone: yes
    update: yes
    force: yes
    version: '{{branch | default("main")}}'

- name: Changing permission of "manage.py", adding "+x"
  file: dest={{project_path}}/manage.py mode=a+x
